version: '2.4'

# Templates:
x-base: &base-service-template
  init: true
  networks:
    local:

services:

  portainer:
    <<: *base-service-template
    image: portainer/portainer:1.24.0
    container_name: portainer.ctn
    command: -p :80
    ports:
      - "9000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sqlserver:
    <<: *base-service-template
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver.ctn
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD:-Password1!}
    ports:
      - "1433:1433"
    healthcheck:
      test: ./opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Password1! -Q "SELECT 1" || exit 1
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 3s

  shower:
    <<: *base-service-template
    image: mirzamerdovic/shower:latest
    container_name: shower.ctn
    environment:
      - SERVER_INSTANCE=sqlserver
      - USER_ID=sa
      - PASSWORD=Password1!
    depends_on:
      - sqlserver
    stdin_open: true
    tty: true
    volumes:
      - ./SqlScripts/:/opt/mssql-tools/shower
    healthcheck:
      test: ./bin/sqlcmd -S sqlserver -U sa -P Password1! -Q "SELECT 1" || exit 1
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 3s

networks:
  local:
    name: local

volumes:
  portainer_data: